### ISSUE TITLE
Datasheet for Death in Custody dataset - Composition

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/data-processing#26]
Create a Datasheet for TJI using [this paper](https://arxiv.org/pdf/1803.09010.pdf) for better data governance. 

Datasheet is a dataset documentation to facilitate better communication between dataset creators and dataset consumers, and encourage the machine learning community to prioritize transparency and accountability. Its format is created by AI researchers from academia (Georgia Tech, Cornell, University of Maryland), industry (Google, Microsoft) and a research institute (AI Now).

Datasheet contains a series of questions that dataset creators can answer. The questions are grouped into sections that roughly match the key stages of the dataset creation, maintenance, and distribution process. Since TJI dataset is already created and maintained, @hongsups will fill out each group of the questions one by one for each dataset.

The questions are normally grouped into: 
- Motivation
- Composition
- Collection process
- Pre-processing/cleaning/labeling
- Uses
- Distribution
- Maintenance

This issue is specifically for *Composition* for the Death in Custody dataset.

**Comment by hongsups** [comment]
Transferred to data-processing since the datasheet addresses how data is preprocessed and handled. Once datasheets are finished, they can be potentially moved back to the original repo.
